export const apiEndpoints = {
  projects: "/api/qony/projects",
  project: (projectId: string) => `/api/qony/projects/${projectId}`,
  projectGraph: (projectId: string) => `/api/qony/projects/${projectId}/graph`,
  projectIngest: (projectId: string) => `/api/qony/projects/${projectId}/ingest`,
  graph: (graphId: string) => `/api/qony/graphs/${graphId}`,
  graphAiEdit: (graphId: string) => `/api/qony/graphs/${graphId}/ai-edit`,
  graphExport: (graphId: string) => `/api/qony/graphs/${graphId}/export`,
  nodeCollection: (graphId: string) => `/api/qony/nodes/${graphId}`,
  node: (nodeId: string) => `/api/qony/nodes/${nodeId}`,
  edgeCollection: (graphId: string) => `/api/qony/edges/${graphId}`,
  edge: (edgeId: string) => `/api/qony/edges/${edgeId}`,
  exportJob: (jobId: string) => `/api/qony/exports/${jobId}`,
  paymentCheckout: "/api/qony/payment/checkout",
  paymentSubscription: "/api/qony/payment/subscription",
  adminUsers: "/api/qony/admin/users",
  adminMetrics: "/api/qony/admin/metrics",
  adminFlags: "/api/qony/admin/flags",
  health: "/health",
  ready: "/ready",
};
